version: '3.7'

services:
  presign-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      #- "5000:5000"
      - "8000:8000"
    environment:
      - S3_BUCKET_NAME=appcd-demo-dogeapi
    volumes:
      - ./docs:/app/docs
